version: '3.8'

services:
  questful-api:
    build:
      context: ./backend
      dockerfile: Dockerfile
    container_name: questful-api
    ports:
      - "8022:8022"
    env_file:
      - ./backend/.env
    restart: unless-stopped
    networks:
      - forge-network

networks:
  forge-network:
    driver: bridge
